spring.application.name=OrderManagementProject
server.port=2020

# Database configuration 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url =jdbc:postgresql://localhost:5432/ordermanagement
# this is an database user name
spring.datasource.username = postgres
# this is an database password 
spring.datasource.password = tushar033  
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
